trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  projectName: 'Umbraco.Forms.Integrations.Crm.Hubspot.OAuthProxy'
  project: 'src/$(projectName)/$(projectName).csproj'
  buildConfiguration: 'Release'
  azureServiceConnection: 'Umbraco Forms Integrations - Umbraco Cloud Services Dev - Hubspot Auth'
  webAppName: 'azapp-forms-hubspot-auth-we-dev-svc'

steps:
- script: dotnet build $(project) --configuration $(buildConfiguration)
  displayName: 'Buid Web App'
- task: DotNetCoreCLI@2
  displayName: 'Publish Web App'
  inputs:
    command: 'publish'
    projects: $(project)
    publishWebProjects: false
- task: AzureWebApp@1
  displayName: 'Deploy Web App'
  inputs:
    azureSubscription: $(azureServiceConnection)
    appName: $(webAppName)
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
- task: AzureAppServiceSettings@1
  displayName: 'Set Web App Settings'
  inputs:
    azureSubscription: $(azureServiceConnection)
    appName: $(webAppName)
    appSettings: |
      [
        {
          "name": "ClientSecret",
          "value": "$(hubSpotAppSecretKey)",
          "slotSetting": false
        }
      ]