trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  projectName: 'Umbraco.Forms.Integrations.Crm.Hubspot.OAuthProxy'
  project: 'src/$(projectName)/$(projectName).csproj'
  buildConfiguration: 'Release'

steps:
- script: dotnet build $(project) --configuration $(buildConfiguration)
  displayName: 'Buid Web App'
- task: DotNetCoreCLI@2
  displayName: 'Publish Web App'
  inputs:
    command: 'publish'
    projects: $(project)
    publishWebProjects: false
#- task: AzureWebApp@1
#  displayName: 'Deploy Web App'
#  inputs:
#    azureSubscription: '<Azure service connection>'
#    appType: 'webAppLinux'
#    appName: '<Name of web app>'
#    package: '$(System.DefaultWorkingDirectory)/**/*.zip'